from __future__ import annotations

from typing import Any


def field(
    name: str,
    label: str,
    required: bool = False,
    kind: str = 'text',
    source_table: str | None = None,
    label_column: str | None = None,
) -> dict[str, Any]:
    return {
        'name': name,
        'label': label,
        'required': required,
        'kind': kind,
        'source_table': source_table,
        'label_column': label_column,
    }


MODULES: list[dict[str, Any]] = [
    {'key': 'customers', 'title': 'Customers', 'table': 'customers', 'description': 'Editable customer master records for ERP, quality, quoting, work orders, and reporting.', 'fields': [field('name', 'Customer name', True), field('code', 'Customer code'), field('contact_name', 'Contact name'), field('email', 'Email', False, 'email'), field('phone', 'Phone'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'suppliers', 'title': 'Suppliers', 'table': 'suppliers', 'description': 'Editable supplier master records for purchasing, outside processing, material sourcing, and quality follow-up.', 'fields': [field('name', 'Supplier name', True), field('code', 'Supplier code'), field('contact_name', 'Contact name'), field('email', 'Email', False, 'email'), field('phone', 'Phone'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'departments', 'title': 'Departments', 'table': 'departments', 'description': 'Editable shop departments used for scheduling, PM, quality trends, and privacy-safe morale indicators.', 'fields': [field('name', 'Department name', True), field('manager_name', 'Manager name'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'reason-codes', 'title': 'Reason Codes', 'table': 'reason_codes', 'description': 'Editable reason codes for RMAs, NCRs, DMRs, rejects, deviations, planning issues, and trend reporting.', 'fields': [field('code', 'Code', True), field('label', 'Label', True), field('category', 'Category', True), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'parts', 'title': 'Parts', 'table': 'parts', 'description': 'Part master foundation for revisions, customer parts, work orders, BOMs, quoting, and quality history.', 'fields': [field('part_number', 'Part number', True), field('revision', 'Revision'), field('customer_id', 'Customer', False, 'select', 'customers', 'name'), field('description', 'Description', False, 'textarea'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'work-orders', 'title': 'Work Orders', 'table': 'work_orders', 'description': 'Work order tracking foundation for quantity, due dates, status, customer linkage, and quality traceability.', 'fields': [field('work_order_number', 'Work order number', True), field('part_id', 'Part', False, 'select', 'parts', 'part_number'), field('customer_id', 'Customer', False, 'select', 'customers', 'name'), field('quantity_ordered', 'Quantity ordered', False, 'number'), field('due_date', 'Due date', False, 'date'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'rma-tracking', 'title': 'RMA Tracking', 'table': 'rma_records', 'description': 'Dedicated RMA tracking for customer returns, dispositions, credits, replacements, and quality linkage.', 'fields': [field('rma_number', 'RMA number', True), field('customer_id', 'Customer', False, 'select', 'customers', 'name'), field('part_id', 'Part', False, 'select', 'parts', 'part_number'), field('work_order_id', 'Work order', False, 'select', 'work_orders', 'work_order_number'), field('reason_code_id', 'Reason code', False, 'select', 'reason_codes', 'code'), field('received_date', 'Received date', False, 'date'), field('quantity_returned', 'Quantity returned', False, 'number'), field('disposition', 'Disposition'), field('status', 'Status'), field('customer_statement', 'Customer statement', False, 'textarea'), field('internal_notes', 'Internal notes', False, 'textarea')]},
    {'key': 'quality-events', 'title': 'Quality Events', 'table': 'quality_events', 'description': 'RMA, NCR, DMR, CAPA, inspection reject, and customer complaint records.', 'fields': [field('event_type', 'Event type', True), field('event_number', 'Event number', True), field('customer_id', 'Customer', False, 'select', 'customers', 'name'), field('part_id', 'Part', False, 'select', 'parts', 'part_number'), field('work_order_id', 'Work order', False, 'select', 'work_orders', 'work_order_number'), field('reason_code_id', 'Reason code', False, 'select', 'reason_codes', 'code'), field('quantity_affected', 'Quantity affected', False, 'number'), field('severity', 'Severity'), field('description', 'Description', True, 'textarea'), field('containment', 'Containment', False, 'textarea'), field('root_cause', 'Root cause', False, 'textarea'), field('corrective_action', 'Corrective action', False, 'textarea'), field('owner', 'Owner')]},
    {'key': 'deviations', 'title': 'Deviation Requests', 'table': 'deviations', 'description': 'Controlled deviation requests with customer, part, work order, disposition, risk assessment, and approval status.', 'fields': [field('deviation_number', 'Deviation number', True), field('customer_id', 'Customer', False, 'select', 'customers', 'name'), field('part_id', 'Part', False, 'select', 'parts', 'part_number'), field('work_order_id', 'Work order', False, 'select', 'work_orders', 'work_order_number'), field('requested_by', 'Requested by'), field('reason', 'Reason', True, 'textarea'), field('proposed_disposition', 'Proposed disposition', False, 'textarea'), field('risk_assessment', 'Risk assessment', False, 'textarea')]},
    {'key': 'documents', 'title': 'Documents', 'table': 'documents', 'description': 'Document control foundation for procedures, drawings, specs, customer files, and ERP references.', 'fields': [field('document_number', 'Document number', True), field('title', 'Title', True), field('revision', 'Revision'), field('document_type', 'Document type', True), field('owner', 'Owner'), field('storage_reference', 'Storage reference'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'pm-assets', 'title': 'PM Assets', 'table': 'pm_assets', 'description': 'Preventive maintenance asset register for equipment, PM frequency, due dates, and department linkage.', 'fields': [field('asset_number', 'Asset number', True), field('name', 'Asset name', True), field('department_id', 'Department', False, 'select', 'departments', 'name'), field('asset_type', 'Asset type'), field('pm_frequency', 'PM frequency'), field('last_pm_date', 'Last PM date', False, 'date'), field('next_pm_date', 'Next PM date', False, 'date'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'clocking-summaries', 'title': 'FPY Clocking Summaries', 'table': 'fpy_clocking_summaries', 'description': 'Aggregate clocking summaries for first-pass yield, rework, scrap, and earned labor trend review.', 'fields': [field('period_start', 'Period start', True, 'date'), field('period_end', 'Period end', True, 'date'), field('department_id', 'Department', False, 'select', 'departments', 'name'), field('part_id', 'Part', False, 'select', 'parts', 'part_number'), field('work_order_id', 'Work order', False, 'select', 'work_orders', 'work_order_number'), field('total_jobs', 'Total jobs', False, 'number'), field('first_pass_jobs', 'First-pass jobs', False, 'number'), field('rework_jobs', 'Rework jobs', False, 'number'), field('scrap_jobs', 'Scrap jobs', False, 'number'), field('labor_hours', 'Labor hours', False, 'number'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'operator-efficiency', 'title': 'Operator Efficiency Baselines', 'table': 'operator_efficiency_baselines', 'description': 'Privacy-safe operator efficiency baselines by department, role group, process, or period for quoting and capacity assumptions.', 'fields': [field('baseline_name', 'Baseline name', True), field('department_id', 'Department', False, 'select', 'departments', 'name'), field('role_group', 'Role group'), field('process_name', 'Process name'), field('period_start', 'Period start', False, 'date'), field('period_end', 'Period end', False, 'date'), field('baseline_hours_per_unit', 'Baseline hours per unit', False, 'number'), field('baseline_units_per_hour', 'Baseline units per hour', False, 'number'), field('confidence_level', 'Confidence level'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'quote-throughput', 'title': 'Quote Throughput Baselines', 'table': 'quote_throughput_baselines', 'description': 'Quoting throughput baselines for intake volume, quote cycle time, engineering review load, and capacity planning.', 'fields': [field('baseline_name', 'Baseline name', True), field('department_id', 'Department', False, 'select', 'departments', 'name'), field('period_start', 'Period start', False, 'date'), field('period_end', 'Period end', False, 'date'), field('quotes_received', 'Quotes received', False, 'number'), field('quotes_completed', 'Quotes completed', False, 'number'), field('average_turnaround_days', 'Average turnaround days', False, 'number'), field('engineering_review_count', 'Engineering review count', False, 'number'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'planning-watchlist', 'title': 'Planning Watchlist', 'table': 'planning_watchlist', 'description': 'Planning, lead-time, schedule-risk, and customer-commitment watchlist for ERP execution.', 'fields': [field('watch_item', 'Watch item', True), field('customer_id', 'Customer', False, 'select', 'customers', 'name'), field('part_id', 'Part', False, 'select', 'parts', 'part_number'), field('work_order_id', 'Work order', False, 'select', 'work_orders', 'work_order_number'), field('risk_type', 'Risk type'), field('lead_time_days', 'Lead time days', False, 'number'), field('due_date', 'Due date', False, 'date'), field('owner', 'Owner'), field('status', 'Status'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'purchasing-watchlist', 'title': 'Purchasing Watchlist', 'table': 'purchasing_watchlist', 'description': 'Purchasing risk watchlist for supplier issues, material availability, purchase timing, and lead-time concerns.', 'fields': [field('watch_item', 'Watch item', True), field('supplier_id', 'Supplier', False, 'select', 'suppliers', 'name'), field('part_id', 'Part', False, 'select', 'parts', 'part_number'), field('material_spec', 'Material spec'), field('required_date', 'Required date', False, 'date'), field('lead_time_days', 'Lead time days', False, 'number'), field('estimated_cost', 'Estimated cost', False, 'number'), field('owner', 'Owner'), field('status', 'Status'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'operating-profiles', 'title': 'Operating Setup Profiles', 'table': 'operating_setup_profiles', 'description': 'Operating setup profile for JIT, hybrid, or inventory-buffered manufacturing mode assumptions.', 'fields': [field('profile_name', 'Profile name', True), field('operating_mode', 'Operating mode'), field('jit_sensitivity', 'JIT sensitivity'), field('buffer_policy', 'Buffer policy', False, 'textarea'), field('inventory_strategy', 'Inventory strategy', False, 'textarea'), field('planning_notes', 'Planning notes', False, 'textarea')]},
    {'key': 'drawing-intake', 'title': 'Customer Drawing Intake', 'table': 'customer_drawing_intake', 'description': 'Customer drawing intake records for quoting resources, review status, revision control, and PDF extraction staging.', 'fields': [field('intake_number', 'Intake number', True), field('customer_id', 'Customer', False, 'select', 'customers', 'name'), field('document_id', 'Document', False, 'select', 'documents', 'document_number'), field('drawing_number', 'Drawing number'), field('drawing_revision', 'Drawing revision'), field('quote_request_number', 'Quote request number'), field('file_reference', 'File reference'), field('review_status', 'Review status'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'pdf-bom-candidates', 'title': 'PDF BOM Candidates', 'table': 'pdf_bom_candidates', 'description': 'Automatically extracted BOM candidate rows from customer drawing PDFs, held for review before use.', 'fields': [field('drawing_intake_id', 'Drawing intake', False, 'select', 'customer_drawing_intake', 'intake_number'), field('candidate_source_page', 'Source page', False, 'number'), field('proposed_part_number', 'Proposed part number'), field('proposed_description', 'Proposed description', False, 'textarea'), field('proposed_quantity', 'Proposed quantity', False, 'number'), field('raw_text', 'Raw extracted text', False, 'textarea'), field('confidence_score', 'Confidence score', False, 'number'), field('review_status', 'Review status'), field('review_notes', 'Review notes', False, 'textarea')]},
    {'key': 'bom-reviews', 'title': 'BOM Reviews', 'table': 'bom_reviews', 'description': 'Human BOM review checkpoint before extracted or imported BOM data is used downstream.', 'fields': [field('review_number', 'Review number', True), field('drawing_intake_id', 'Drawing intake', False, 'select', 'customer_drawing_intake', 'intake_number'), field('reviewed_by', 'Reviewed by'), field('review_status', 'Review status'), field('approved_for_use', 'Approved for use'), field('risk_notes', 'Risk notes', False, 'textarea'), field('decision_notes', 'Decision notes', False, 'textarea')]},
    {'key': 'material-catalog', 'title': 'Material Catalog', 'table': 'material_catalog', 'description': 'Approved supplier and material catalog for quote material assignment, cost, standard length, pieces, and lead-time estimates.', 'fields': [field('material_code', 'Material code', True), field('supplier_id', 'Supplier', False, 'select', 'suppliers', 'name'), field('material_description', 'Material description', True, 'textarea'), field('material_spec', 'Material spec'), field('standard_length', 'Standard length'), field('unit_cost', 'Unit cost', False, 'number'), field('lead_time_days', 'Lead time days', False, 'number'), field('approval_status', 'Approval status'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'quote-material-drafts', 'title': 'Quote Material Drafts', 'table': 'quote_material_assignment_drafts', 'description': 'Automatic quote material assignment drafts for review before quote use.', 'fields': [field('draft_number', 'Draft number', True), field('drawing_intake_id', 'Drawing intake', False, 'select', 'customer_drawing_intake', 'intake_number'), field('bom_candidate_id', 'BOM candidate', False, 'select', 'pdf_bom_candidates', 'proposed_part_number'), field('material_catalog_id', 'Material catalog item', False, 'select', 'material_catalog', 'material_code'), field('part_id', 'Part', False, 'select', 'parts', 'part_number'), field('estimated_pieces_required', 'Estimated pieces required', False, 'number'), field('estimated_material_cost', 'Estimated material cost', False, 'number'), field('estimated_lead_time_days', 'Estimated lead time days', False, 'number'), field('assignment_confidence', 'Assignment confidence'), field('review_status', 'Review status'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'dashboard-metrics', 'title': 'Dashboard Metrics', 'table': 'dashboard_metrics', 'description': 'Dashboard metric snapshots for ERP health, quality, delivery, cost, purchasing, throughput, and morale indicators.', 'fields': [field('metric_date', 'Metric date', True, 'date'), field('metric_name', 'Metric name', True), field('metric_category', 'Metric category'), field('department_id', 'Department', False, 'select', 'departments', 'name'), field('metric_value', 'Metric value', False, 'number'), field('target_value', 'Target value', False, 'number'), field('status', 'Status'), field('notes', 'Notes', False, 'textarea')]},
    {'key': 'morale-snapshots', 'title': 'Morale Snapshots', 'table': 'morale_snapshots', 'description': 'Privacy-safe aggregate morale pulse tracking by department, period, overtime, PTO pressure, absences, and turnover.', 'fields': [field('period_start', 'Period start', True, 'date'), field('period_end', 'Period end', True, 'date'), field('department_id', 'Department', False, 'select', 'departments', 'name'), field('overtime_hours', 'Overtime hours', False, 'number'), field('exhausted_pto_count', 'Exhausted PTO count', False, 'number'), field('unscheduled_absence_count', 'Unscheduled absence count', False, 'number'), field('unpaid_timeoff_count', 'Unpaid time off count', False, 'number'), field('turnover_count', 'Turnover count', False, 'number'), field('staffing_notes', 'Staffing notes', False, 'textarea'), field('quality_risk_notes', 'Quality risk notes', False, 'textarea')]},
]

MODULE_BY_KEY = {module['key']: module for module in MODULES}
